# ethnicity_mapping dictionary
ethnicity_mapping = {
    'United States': 'White European',
    'Brazil': 'South American',
    'Spain': 'White European',
    'Egypt': 'Middle Eastern',
    'New Zealand': 'Pasifika',
    'Bahamas': 'Black',
    'Burundi': 'African',
    'Austria': 'White European',
    'Argentina': 'South American',
    'Jordan': 'Middle Eastern',
    'Ireland': 'White European',
    'United Arab Emirates': 'Middle Eastern',
    'Afghanistan': 'South Asian',
    'Lebanon': 'Middle Eastern',
    'United Kingdom': 'White European',
    'South Africa': 'Black',
    'Italy': 'White European',
    'Pakistan': 'South Asian',
    'Bangladesh': 'South Asian',
    'Chile': 'South American',
    'France': 'White European',
    'China': 'Asian',
    'Australia': 'White European',
    'Canada': 'White European',
    'Saudi Arabia': 'Middle Eastern',
    'Netherlands': 'White European',
    'Romania': 'White European',
    'Sweden': 'White European',
    'Tonga': 'Pasifika',
    'Oman': 'Middle Eastern',
    'India': 'South Asian',
    'Philippines': 'Asian',
    'Sri Lanka': 'South Asian',
    'Sierra Leone': 'African',
    'Ethiopia': 'African',
    'Viet Nam': 'Asian',
    'Iran': 'Middle Eastern',
    'Costa Rica': 'Latino',
    'Germany': 'White European',
    'Mexico': 'Latino',
    'Russia': 'White European',
    'Armenia': 'White European',
    'Iceland': 'White European',
    'Nicaragua': 'Latino',
    'Hong Kong': 'Asian',
    'Japan': 'Asian',
    'Ukraine': 'White European',
    'Kazakhstan': 'Asian',
    'American Samoa': 'Pasifika',
    'Uruguay': 'South American',
    'Serbia': 'White European',
    'Portugal': 'White European',
    'Malaysia': 'Asian',
    'Ecuador': 'Latino',
    'Niger': 'African',
    'Belgium': 'White European',
    'Bolivia': 'South American',
    'Aruba': 'Latino',
    'Finland': 'White European',
    'Turkey': 'White European',
    'Nepal': 'South Asian',
    'Indonesia': 'Asian',
    'Angola': 'African',
    'Azerbaijan': 'Middle Eastern',
    'Iraq': 'Middle Eastern',
    'Czech Republic': 'White European',
    'Cyprus': 'Middle Eastern'
}

# ethnicity_code_mapping dictionary
ethnicity_code_mapping = {
    'White European': 0,
    'South American': 1,
    'Asian': 2,
    'Black': 3,
    'Middle Eastern': 4,
    'South Asian': 5,
    'African': 6,
    'Latino': 7,
    'Pasifika': 8,
    'Others': 9
}

# aq_questions list
aq_questions = [
    "I often notice small sounds when others do not",
    "I usually concentrate more on the whole picture, rather than the small details",
    "I find it easy to do more than one thing at once",
    "If there is an interruption, I can switch back to what I was doing very quickly",
    "I find it easy to 'read between the lines' when someone is talking to me",
    "I know how to tell if someone listening to me is getting bored",
    "When I'm reading a story, I find it difficult to work out the characters' intentions",
    "I like to collect information about categories of things",
    "I find it easy to work out what someone is thinking or feeling just by looking at their face",
    "I find it difficult to work out people's intentions"
]
