apiVersion: v1
kind: Service
metadata:
  name: asd-screening-service
spec:
  selector:
    app: asd-screening-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
